### ISSUE TITLE
ORP C Client: Error reported when SYNC packet received

### ISSUE THREAD

**Issue by imorrisonca** [SierraWireless/octave-orp#2]
A user reported that an error is printed when the SYNC packet is received:
```
orp > ERRO | src/orpProtocol.c, line: 736 | SYN|SYNACK|ACK byte 1 not decoded

Received: 'Y13031T1607935415.000000', (28 bytes) 
       Type     : 13 (Synchronization, sync) 
       Data type: -1 
       Sequence : 12337 
       Timestamp: 1607935415.000000
```
This is a known issue - the orpProtocol routines do not decode part of these packets.  This will be fixed soon.

**Comment by Zumtak** [comment]
Good job it now works for me!
However, no response is sent back... and it keeps sending me `sync` packets.

**Comment by imorrisonca** [comment]
Hi Antoine,

Yes, the ORP service will continue sending the SYNC packets until it receives an acknowledgement or a valid request from the client.  More detail can be found here:
https://docs.octave.dev/docs/octave-resource-protocol#sync-version-2-and-up

We will add an automatic acknowledgement to this sample app in an upcoming revision.  For now, the SYNC can be acknowledged manually by issuing:
```
orp > reply synack
```
Thanks,
Ian
